### ISSUE TITLE
Suport diferentiere tip de contract electricitate/gaz

### ISSUE THREAD

**Issue by Alfy1080** [cnecrea/eonromania#15]
### Ați citit secțiunea FAQ.md?

Da, am citit secțiunea FAQ.md și nu am găsit răspunsul la problema mea.

### Descrieți problema

Salutare.

In primul rand multumesc pentru efortul depus in crearea acestei integrari. De mult mi-am dorit o integrare cu furnizorul de energie in Home Assistant. :) 

Eu am contract E.ON Duo deci pentru instalarea integrarii am folosit username, parola si CI separat pentru electricitate si gaz. Pentru integrarea pe contractul de electricitate am buton de trimitere index insa imi cere exact aceeasi entitate ca si cea pentru transmiterea indexului de gaz (input_number.gas_meter_reading).
Este posibila diferentierea intre cele doua tipuri de contracte integrate in HA ca sa am doua entitati separate pentru transmiterea indexului de gaz si cel de curent?

De asemenea o alta problema (mica) ar fi faptul ca in integrarea contractului de electricitate, toate valorile sunt prezentate in metri cubi. Presupun ca integrarea nu are de unde sa stie ce fel de contract am adaugat, dar ma gandeam ca o varianta ar fi ca in config flow sa adaugi un dropdown cu optiunile "Electricitate" si "Gaz" iar in functie de selectia respectiva, masuratorile sa fie in metri cubi sau kWh. 

Multumesc! :)

### Versiunea integrării

1.5.0

### Loguri relevante

```yaml
Logger: custom_components.eonromania.button
Source: custom_components/eonromania/button.py:85
integration: E-ON Romania (documentation, issues)
First occurred: 4:26:21 PM (1 occurrences)
Last logged: 4:26:21 PM

Entitatea input_number.gas_meter_reading nu este definită.
```

### Ați încercat să dați restart?

Da

### Sistem de operare

Debian 12
