### ISSUE TITLE
Data scadenta factura eronata

### ISSUE THREAD

**Issue by Katod2024** [cnecrea/eonromania#5]
Pe langa faptul ca nu imi apare senzorul de index (am inteles ca e indisponibil de la eon din 01.01) am o factura care este scadenta in 27.01 dar in integrare apare scadenta depasita.
![restanta](https://github.com/user-attachments/assets/c7bfcf0f-94d1-48f3-8f5e-e54daf9ad13a)
![factura](https://github.com/user-attachments/assets/cb9fc4b8-df34-4827-85e4-5423d4c01415)

**Comment by cnecrea** [comment]
Mersi de info. Am să verific codul dacă face funcția corect.

Revin cu un update

**Comment by cnecrea** [comment]
salut,

Am actualizat codul pentru a rezolva problema. Asigură-te că actualizezi integrarea prin HACS pentru a aplica modificările următoare:https://github.com/cnecrea/eonromania/commit/e08b23473b6e9b24bcc4f21e7d4415075221c599, https://github.com/cnecrea/eonromania/commit/99c4fddc44e60606dad48c3bd08c23c008b8bb8d

Îți multumesc pentru feedback!

---

## ☕ Susține dezvoltatorul

Dacă ți-a plăcut această integrare și vrei să sprijini munca depusă, **invită-mă la o cafea**! 🫶  
Nu costă nimic, iar contribuția ta ajută la dezvoltarea viitoare a proiectului. 🙌  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Susține%20dezvoltatorul-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijin și apreciez fiecare gest de susținere! 🤗

**Comment by Katod2024** [comment]
Salut,
Am actualizat integrarea prin HACS la versiunea e08b234 insa versiunea 99c4fdd nu imi mai apare ulterior ca optiune de actualizare.
Mersi

**Comment by cnecrea** [comment]
salut,

Nu am înțeles exact ce întrebi. Suma facturii este corectă? Scadența facturii este incorectă?

La scadență, trebuie să ținem cont de faptul că ziua de 27.01.2025 nu este inclusă în calcul. În această zi apare un mesaj diferit, și anume:

```yaml
due_message = f"De achitat astăzi, {datetime.now().strftime('%d.%m.%Y')}: {issued_value:.2f} lei"
```

Pentru claritate, sistemul calculează scadența până pe 26.01.2025, excluzând ziua de 27.01.2025. Deși ar fi logic să includ această zi, o consider drept „ziua X” – ziua în care plata trebuie efectuată obligatoriu.

De aceea, am ales să afișez un mesaj distinct și să o exclud din “calcul”.

Dacă ideea nu este clară, putem discuta mai detaliat.

## ☕ Susține dezvoltatorul

Dacă ți-a plăcut această integrare și vrei să sprijini munca depusă, **invită-mă la o cafea**! 🫶  
Nu costă nimic, iar contribuția ta ajută la dezvoltarea viitoare a proiectului. 🙌  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Susține%20dezvoltatorul-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijin și apreciez fiecare gest de susținere! 🤗

**Comment by Katod2024** [comment]
Scadenta este corecta. Nu stiam de ce nu e inclusa in calcul si data de 27.01. Acum am inteles cum e cu data scadentei.
Suma facturii este de 778,12 - suma afisata corect in dreptul Facturii 1 impreuna cu scadenta. Eu facand o plata anticipata de 367,68 a ramasa de plata din aceasta factura la data emiterii suma de 410,44 care ar trebui sa apara la Total neachitat (cum aparea initial cand nu afisa corect data scadentei - vezi prima poza)

**Comment by cnecrea** [comment]
> Scadenta este corecta. Nu stiam de ce nu e inclusa in calcul si data de 27.01. Acum am inteles cum e cu data scadentei. Suma facturii este de 778,12 - suma afisata corect in dreptul Facturii 1 impreuna cu scadenta. Eu facand o plata anticipata de 367,68 a ramasa de plata din aceasta factura la data emiterii suma de 410,44 care ar trebui sa apara la Total neachitat (cum aparea initial cand nu afisa corect data scadentei - vezi prima poza)

Salut! Ai putea să rulezi un script Python și să îmi furnizezi output-ul?
Dacă da, aici ai scriptul:


```python
import requests
import json

# Endpoint de autentificare
login_url = "https://api2.eon.ro/users/v1/userauth/login"

# Datele pentru autentificare
username = "ADRESA_EMAIL"
password = "PAROLA_TA"
account_contract = "COD_INCASARE"  # Adaugă codul incasării aici cu 00 înainte

# Payload-ul pentru autentificare
login_payload = {
    "username": username,
    "password": password,
    "rememberMe": False,
}

# Anteturile, inclusiv cheia de subscripție
headers = {
    "Accept": "application/json, text/plain, */*",
    "Content-Type": "application/json",
    "Ocp-Apim-Subscription-Key": "674e9032df9d456fa371e17a4097a5b8",  # Înlocuiește cu cheia corectă dacă este diferită
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
}

# Funcție pentru afișarea JSON formatat
def display_formatted_json(title, data):
    try:
        formatted_data = json.dumps(data, indent=4, ensure_ascii=False)
        print(f"{title}:\n{formatted_data}")
    except (ValueError, TypeError) as e:
        print(f"{title}:\nEroare la formatarea JSON: {e}")

# Cererea POST pentru autentificare
response = requests.post(login_url, json=login_payload, headers=headers)

if response.status_code == 200:
    auth_token = response.json().get("accessToken")
    if auth_token:
        print("Autentificare reușită! Token:", auth_token)

        # Continuă cu cererile ulterioare dacă autentificarea reușește
        headers["Authorization"] = f"Bearer {auth_token}"

        # Exemplu: Obține detalii despre utilizator
        user_details_url = f"https://api2.eon.ro/invoices/v1/invoices/invoice-balance?accountContract={account_contract}"
        response = requests.get(user_details_url, headers=headers)
        if response.status_code == 200:
            display_formatted_json("Detalii utilizator", response.json())
        else:
            print("Eroare la obținerea detaliilor utilizator:", response.status_code, response.text)
    else:
        print("Autentificare reușită, dar nu s-a primit un token valid.")
else:
    print("Autentificare eșuată:", response.status_code, response.text)

```

## ☕ Susține dezvoltatorul

Dacă ți-a plăcut această integrare și vrei să sprijini munca depusă, **invită-mă la o cafea**! 🫶  
Nu costă nimic, iar contribuția ta ajută la dezvoltarea viitoare a proiectului. 🙌  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Susține%20dezvoltatorul-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijin și apreciez fiecare gest de susținere! 🤗

**Comment by Katod2024** [comment]
M-ai incuiat aici... Cunostintele mele intr-ale HA si IT in general sunt limitate (eu fiind de profesie farmacist)... totusi, ma straduiesc...
Am instalat pyscript din HACS, am creat un fisier test_eon.py in folderul pyscript nou creat si la incarcarea scriptului py, in log apare eroarea:
2025-01-05 16:56:37.969 ERROR (MainThread) [custom_components.pyscript.file.test_eon] Exception in </config/pyscript/test_eon.py> line 36:
    response = requests.post(login_url, json=login_payload, headers=headers)

**Comment by cnecrea** [comment]
Te înțeleg, nu te stresa.

Știi să faci debug în Home Assistant?

Adaugă următoarele linii în fișierul configuration.yaml, apoi dă restart la Home Assistant. După aceea, mergi în fișierul home-assistant.log și copiează informațiile relevante, pe care să mi le atașezi aici. Atenție, exclude datele sensibile (utilizatori, parole).

```yaml
logger:
  default: warning
  logs:
    custom_components.eonromania: debug
    homeassistant.const: critical
    homeassistant.loader: critical
    homeassistant.helpers.frame: critical

**Comment by Katod2024** [comment]
M-am uitat prin el si nu pare sa fie niciun user si parola asa ca am pus intregul log.
[home-assistant.log](https://github.com/user-attachments/files/18311451/home-assistant.log)

**Comment by cnecrea** [comment]
Mulțumesc! Acum am înțeles clar unde este problema și care este comportamentul celor de la EON. 

JSON-ul arată clar că issuedValue reprezintă valoarea facturii emise, însă, având în vedere că ai achitat 367,68, suma restantă ar trebui să fie balanceValue = 410.44.

Voi remedia problema comportamentului în codul integrării și voi ține cont de acest aspect. 

Îți mulțumesc pentru răbdare!

```yaml
[
    {
        "fiscalNumber": "0000010XXXXX3240",
        "maturityDate": "27.01.2025",
        "emissionDate": "27.12.2024",
        "disconnectionDate": null,
        "printDate": "23.12.2024",
        "archiveDate": "24.12.2024",
        "issuedValue": 778.12,
        "balanceValue": 410.44,
        "balanceValueDetail": null,
        "issuedValueDetail": null,
        "invoiceNumber": "011XX21X0X81",
        "state": "0",
        "type": "Consum",
        "sector": "02",
        "cb": "210291307022000105317032400020000077812",
        "companyCode": "1930",
        "electronic": true,
        "accountContract": "002102XXX07X",
        "hasDetails": true,
        "hasPdf": true,
        "isDownloadable": true,
        "canPay": true,
        "canActivate": false,
        "invoiceTypeCode": "FI",
        "paymentInstalment": false,
        "meterDetails": null,
        "refund": false,
        "refundInProcess": false,
        "digitalInvoice": false,
        "refundRequestCreatedAt": null,
        "prosumId": null,
        "storno": null
    }
]
```

## ☕ Susține dezvoltatorul

Dacă ți-a plăcut această integrare și vrei să sprijini munca depusă, **invită-mă la o cafea**! 🫶  
Nu costă nimic, iar contribuția ta ajută la dezvoltarea viitoare a proiectului. 🙌  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Susține%20dezvoltatorul-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijin și apreciez fiecare gest de susținere! 🤗
