### ISSUE TITLE
Apelare buton "Trimite Index"

### ISSUE THREAD

**Issue by CarpeDiemRo** [cnecrea/eonromania#8]
Poți, te rog, să detaliezi modalitatea prin care se poate apela funcționalitatea de trimitere a indexului. Din ce văd ea nu este definită că și serviciu, prin urmare nu este afișată sub Actions category.

**Comment by cnecrea** [comment]
salut!

Automatizare, apasă buton.

**Comment by cnecrea** [comment]
Ai rezolvat problema, te-ai descurcat?

**Comment by CarpeDiemRo** [comment]
Mă tem că nu am înțeles la ce te referi prin Automatizare, Apasă buton.

**Comment by cnecrea** [comment]
Ce versiune de integrare folosesti? 1.0.0 sau 1.1.0? Din cate observ, esti la versiunea veche.

**Comment by cnecrea** [comment]
Acum, dupa update, ai vazut si butonul? Daca vrei, poti sa-mi scrii pe FB si o lamurim mai bine.

**Comment by CarpeDiemRo** [comment]
Pe ultima. Iată un printscreen ![Screenshot_2025-01-11-19-21-19-79_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/b804cb58-1216-465f-b1c1-52a1adfd4727)

**Comment by cnecrea** [comment]
Aceea nu este ultima, ultima este 1.1.0. Du-te la HACS, da-i pe 3 punctulete in dreptul integrarii si "Actualizeaza informatiile"

<img width="1648" alt="image" src="https://github.com/user-attachments/assets/d31e263c-5f79-49e1-b8d1-62c23f9f05e4" />

**Comment by CarpeDiemRo** [comment]
Am făcut redownload și a apărut. 

Am deja un entity state cu indexul curent. Care ar fi sintaxa pentru automatizare?

**Comment by CarpeDiemRo** [comment]
Din documentație văd că se poate numai prin input_number.gas_meter_reading. 

Mda. M-ar fi ajutat dacă ar fi fost definit că și serviciu prin care se pot pasa orice entitate de tip integer. 

Mă gândesc că ar fi mult mai versatil așa și i-ar ajuta și pe cei care citesc consumul direct de pe centrală. 

Între timp mă voi gândi la un workaround.  Mulțumesc mult pentru informații. Multe aprecieri pentru munca depusă.

**Comment by cnecrea** [comment]
Deci, butonul se apasă automatizat, sau manual. Cum dorești.

Nu este nevoie să fie „un serviciu” pentru a putea fi apelat.

De exemplu, eu am un cititor de contor care înregistrează impulsurile și le salvează în input_number.gas_meter_reading (mai exact, corecția indexului contorului).

<img width="452" alt="image" src="https://github.com/user-attachments/assets/cb36c082-7900-45aa-9ab5-f9d240c34aec" />


Și dacă ar fi să ne uităm puțin peste codul din buttons.py, observăm că, atunci când se apasă, acesta preia datele din…


```yaml
    async def async_press(self):
        """Execută trimiterea indexului."""
        cod_incasare = self.config_entry.data.get("cod_incasare", "necunoscut")
        try:
            # Obține indexValue din input_number
            gas_meter_state = self.coordinator.hass.states.get("input_number.gas_meter_reading")
            if not gas_meter_state:
                _LOGGER.error("Entitatea input_number.gas_meter_reading nu este definită.")
                return

            index_value = int(float(gas_meter_state.state))
            # Obține ablbelnr din datele coordinatorului
            citireindex_data = self.coordinator.data.get("citireindex")
            if not citireindex_data:
                _LOGGER.error("Nu s-au găsit date pentru citireindex.")
                return

            ablbelnr = None
            devices = citireindex_data.get("indexDetails", {}).get("devices", [])
            for device in devices:
                indexes = device.get("indexes", [])
                if indexes:
                    ablbelnr = indexes[0].get("ablbelnr")
                    break

            if not ablbelnr:
                _LOGGER.error("ID intern citire contor (SAP) nu a fost găsit.")
                return

            # Apelează metoda din API client
            await self.coordinator.api_client.async_trimite_index(
                account_contract=cod_incasare,
                ablbelnr=ablbelnr,
                index_value=index_value,
            )

            await self.coordinator.async_request_refresh()
            _LOGGER.info("Indexul a fost trimis cu succes pentru codul de încasare %s", cod_incasare)
        except Exception as e:
            _LOGGER.error("Eroare la trimiterea indexului pentru codul de încasare %s: %s", cod_incasare, e)

```


Ca urmare, se poate crea o automatizare care să apese butonul dorit la o anumită oră, într-o anumită zi.

Un exemplu de automatizare ar fi următorul: în data de 9 a fiecărei luni, la ora 9:00, îmi trimite un mesaj SMS pe telefon cu consumul înregistrat, iar la ora 12:00, în aceeași zi, trimite automat indexul către EON.

```yaml
alias: Automatizare nouă
description: >-
  Trimite notificări la ora 09:00 și apasă butonul pentru trimiterea indexului
  la ora 12:00.
triggers:
  - at: "09:00:00"
    trigger: time
  - at: "12:00:00"
    trigger: time
conditions:
  - condition: template
    value_template: "{{ now().day == 9 }}"
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.now.hour == 9 }}"
        sequence:
          - metadata: {}
            data:
              target: 40730040302
              message: >-
                E·ON GAZ (mesaj automat): Pentru luna {{
                states('sensor.current_month_translated') }}, noul index este de
                {{ (states('input_number.gas_meter_reading') | float | round(0))
                }} {{ state_attr('sensor.index_curent', 'unit_of_measurement')
                }}
            alias: SMS pe telefon
            action: notify.smsto
        alias: "Optiunea 1: Trimite SMS la ora 09:00"
      - conditions:
          - condition: template
            value_template: "{{ trigger.now.hour == 12 }}"
        sequence:
          - metadata: {}
            data: {}
            target:
              entity_id: button.eonromania_trimite_index_002103870166
            action: button.press
        alias: "Optiunea 2: Trimite index la EON la ora 12:00"
mode: single

```


Pe de altă parte, referitor la ceea ce spui, este imposibil să mulțumești pe toată lumea. Acesta este un lucru standard. Fiecare își poate personaliza HA așa cum dorește, dacă își dorește funcționalitățile X, Y sau Z.
